[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my_learning_package"
version = "0.0.1"
authors = [
  { name = "NyuB" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.10"
